# Install dependencies only when needed
FROM public.ecr.aws/bitnami/node:18.16.0 AS deps
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM public.ecr.aws/bitnami/node:18.16.0 AS builder
ARG ENV_VARS
ENV ENV_VARS ${ENV_VARS}
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN yarn run build-functions
RUN yarn install --production --ignore-scripts --prefer-offline

# Production image, copy all the files and run next
FROM public.ecr.aws/bitnami/node:18.16.0 AS runner

# Install and use libjemalloc to prevent sharp memory leaks
# ref: https://github.com/lovell/sharp/issues/955#issuecomment-475532037
RUN apt-get update && apt-get install --force-yes -yy \
  libjemalloc2 \
  darktable \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV NODE_ENV production


RUN addgroup --gid 1001 --system nodejs
RUN adduser --system nextjs --uid 1001

# You only need to copy next.config.js if you are NOT using the default configuration
# COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.env ./.env

ARG BRANCH_NAME
ENV DD_VERSION ${BRANCH_NAME}

RUN npm install pm2 dotenv -g

# Change memory allocator to avoid leaks
# ref: https://github.com/lovell/sharp/issues/955#issuecomment-475532037
# ref: https://github.com/Unitech/pm2/issues/4375#issuecomment-1003566720
# ref: https://github.com/nodejs/help/issues/1518#issuecomment-997221787
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
RUN ls -la /usr/lib/x86_64-linux-gnu/
RUN echo "LD_PRELOAD=/usr/local/lib/libjemalloc.so.2" >> /etc/environment
RUN echo "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2" >> /etc/ld.so.preload

USER nextjs

EXPOSE 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

CMD pm2-runtime start npm --name 'web-client' --max-memory-restart 6G -- run start:qw
