// Env vars for the tests
// If the value doesn't matter, just add the env name to the below array
// Else set process.env[varName] = value below the `forEach` block
[
  "BLEND_INGREDIENTS_BUCKET",
  "HERO_IMAGES_BUCKET",
  "AWS_CLOUD_ACCESS_KEY_ID",
  "AWS_CLOUD_REGION",
  "AWS_CLOUD_SECRET_ACCESS_KEY",
  "BATCH_DYNAMODB_TABLE",
  "BLEND_DYNAMODB_TABLE",
  "BLEND_GEN_QUEUE_URL",
  "BLEND_INGREDIENTS_BUCKET",
  "BLEND_VERSIONED_DYNAMODB_TABLE",
  "CONFIG_DYNAMODB_TABLE",
  "HERO_IMAGES_BUCKET",
  "HERO_IMAGES_DYNAMODB_TABLE",
  "IPAPI_ACCESS_KEY",
  "NEXT_PUBLIC_OUTPUT_BASE_PATH",
  "NEXT_PUBLIC_SELF_BASE_PATH",
  "RECIPE_DYNAMODB_TABLE",
  "RECIPE_INGREDIENTS_BUCKET",
  "RECIPE_LISTS_DYNAMODB_TABLE",
  "RECO_ENGINE_BASE_URL",
  "TOOLKIT_BASE_PATH",
  "USER_DYNAMODB_TABLE",
  "VES_API_BASE_PATH",
  "WEB_USER_ASSETS_BUCKET",
  "BRANDING_DYNAMODB_TABLE",
  "BRANDING_DYNAMODB_USER_ID_INDEX",
  "BRANDING_BUCKET",
  "REVENUECAT_API_BASE_PATH",
  "REVENUECAT_API_KEY",
].forEach((envVar) => {
  process.env[envVar] = "whatever";
});
process.env.FIREBASE_SERVICE_KEY = {};
process.env.NEXT_PUBLIC_FIREBASE_APP_CLIENT_CONFIG = {};
