export const TYPES = {
  DynamoDB: Symbol.for("DynamoDB"),
  BatchService: Symbol.for("BatchService"),
  BlendService: Symbol.for("BlendService"),
  UploadService: Symbol.for("UploadService"),
  UserService: Symbol.for("UserService"),
  BatchActionService: Symbol.for("BatchActionService"),
  BatchTaskQueue: Symbol.for("BatchTaskQueue"),
  SuggestionService: Symbol.for("SuggestionService"),
  HeroImageService: Symbol.for("HeroImageService"),
  ImageUploadEventQueue: Symbol.for("ImageUploadEventQueue"),
  RemoveBgService: Symbol.for("RemoveBgService"),
  BrandingService: Symbol.for("BrandingService"),
  RecipeService: Symbol.for("RecipeService"),
  InterServiceAuth: Symbol.for("InterServiceAuth"),
  Firebase: Symbol.for("Firebase"),
  UserRepo: Symbol.for("UserRepo"),
};
